name = "Astatine+"
license = "MIT"
description = "Based on Astatine"

tags = ["blog", "minimal", "personal", "responsive", "dark"]
features = ["blog", "taxonomies", "privacy", "dark"]
min_version = 0.25

[author]
  name = "Patrick Bell"

[original]
  name = "Hugo Cisneros"
  homepage = "https://hugocisneros.com"
